# site properties and page defaults
title: Bioinformatics solutions for molecular biology
subtitle: 
description: The VituloLab is a team of researchers at the University of Verona, Department of Biotechnology, where computational methods drive discovery. We tackle biological questions by designing adaptable bioinformatic and statistical approaches, building custom pipelines, and developing new methods tailored to the needs of each project. From microbial communities to genomic and omics data, we explore the molecular complexity of life. Through collaborations with clinicians, biotechnologists, and industry partners, we transform data into meaningful insights that advance both fundamental biology and applied innovation.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: nicola.vitulo@univr.it
  orcid: 
  google-scholar: 
  github: VituloLab
  twitter: 
  youtube: 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
